export default [
    {
        id: "link0",
        name: "Link #0",
        url: "#0",
        added: "2022-03-12",
        description: "This is link 0.",
        enabled: true,
    },
    {
        id: "link1",
        name: "Link #1",
        url: "#1",
        added: "2022-03-12",
        description: "This is link 1.",
        enabled: true,
    },
    {
        id: "link2",
        name: "Link #2",
        url: "#2",
        added: "2022-03-12",
        description: "This is link 2.",
        enabled: true,
    },
    {
        id: "link3",
        name: "Link #3",
        url: "#3",
        added: "2022-03-12",
        description: "This is link 3.",
        enabled: true,
    },
    {
        id: "link4",
        name: "Link #4",
        url: "#4",
        added: "2022-03-12",
        description: "This is link 4.",
        enabled: false,
    },
    {
        id: "link5",
        name: "Link #5",
        url: "#5",
        added: "2022-03-12",
        description: "This is link 5.",
        enabled: true,
    },
    {
        id: "link6",
        name: "Link #6",
        url: "#6",
        added: "2022-03-12",
        description: "This is link 6.",
        enabled: true,
    },
    {
        id: "link7",
        name: "Link #7",
        url: "#7",
        added: "2022-03-12",
        description: "This is link 7.",
        enabled: true,
    },
    {
        id: "link8",
        name: "Link #8",
        url: "#8",
        added: "2022-03-12",
        description: "This is link 8.",
        enabled: true,
    },
    {
        id: "link9",
        name: "Link #9",
        url: "#9",
        added: "2022-03-12",
        description: "This is link 9.",
        enabled: false,
    },
    {
        id: "link10",
        name: "Link #10",
        url: "#10",
        added: "2022-03-12",
        description: "This is link 10.",
        enabled: false,
    },
    {
        id: "link11",
        name: "Link #11",
        url: "#11",
        added: "2022-03-12",
        description: "This is link 11.",
        enabled: true,
    },
]
