export default [
    {
        id: "dear_mother",
        name: "Dear Mother",
        url: "https://umaruru.neocities.org/webring_test/test_pages/dear_mother/",
        added: "2025-03-14",
        description: "Poems for the dear mother.",
    },
    {
        id: "clouds",
        name: "Clouds are cool",
        url: "https://umaruru.neocities.org/webring_test/test_pages/clouds/",
        added: "2025-03-14",
        description: "I like clouds.",
    },
    {
        id: "horse",
        name: "Horse 🐴",
        url: "https://umaruru.neocities.org/webring_test/test_pages/horse/",
        added: "2025-03-14",
        description: "Pocotó horsey.",
    },
    {
        id: "infinite",
        name: "💔🤘🎸 Infinite 🎸🤘💔",
        url: "https://umaruru.neocities.org/webring_test/test_pages/infinite/",
        added: "2025-03-14",
        description: "That's what is takes to be infinite",
    },
    {
        id: "mouse",
        name: "mouse 🧀",
        url: "https://umaruru.neocities.org/webring_test/test_pages/mouse/",
        added: "2025-03-14",
        description: "🐭 🐭 🐭",
    },
    {
        id: "umaruru",
        name: "umaruru",
        url: "https://umaruru.neocities.org/webring_test/test_pages/umaruru/",
        added: "2025-03-14",
        description: "umaruru's page",
    },
    {
        id: "hot",
        name: "Too hot",
        url: "https://umaruru.neocities.org/webring_test/test_pages/hot/",
        added: "2025-03-14",
        description: "omg it's so hot",
    },
    {
        id: "children",
        name: "My children",
        url: "https://umaruru.neocities.org/webring_test/test_pages/children/",
        added: "2025-03-14",
        description: "My offspring",
    },
    {
        id: "context",
        name: "Context for these links",
        url: "https://umaruru.neocities.org/webring_test/test_pages/context/",
        added: "2025-03-14",
        description: "Explaining what's going on.",
    },
    {
        id: "math",
        name: "Matemática",
        url: "https://umaruru.neocities.org/webring_test/test_pages/math/",
        added: "2025-03-15",
        description: "Matemática do amor 🍫",
    },
    {
        id: "enough",
        name: "Enough",
        url: "https://umaruru.neocities.org/webring_test/test_pages/enough/",
        added: "2025-03-15",
        description: "That's enough pages, isn't it?",
    },
    {
        id: "branches",
        name: "Branches???",
        url: "https://umaruru.neocities.org/webring_test/test_pages/branches/",
        added: "2025-03-15",
        description: "Branches are so confusing.",
    },
    {
        id: "ability",
        name: "Ability",
        url: "https://umaruru.neocities.org/webring_test/test_pages/ability/",
        added: "2025-03-16",
        description: "Look what I can do",
    },
    {
        id: "tijolophone",
        name: "Tijolophone",
        url: "https://umaruru.neocities.org/webring_test/test_pages/tijolophone/",
        added: "2025-03-31",
        description: "Me liga amiga, eu quero fugir daqui.",
    },
]
